### ISSUE TITLE
Remove Docker credentials on action completion

### ISSUE THREAD

**Issue by diepes** [mr-smithers-excellent/docker-build-push#106]
Used the action for the first time, and it worked without issues.

I see this warning regarding the password, and a link to some vague documentation about using a keyring to fix it.

Is this warning expected ?
Is there a way to fix/improve secret management ?

From Action log's
```
Run mr-smithers-excellent/docker-build-push@v5
Docker image name created: docker.io/***/debug
Logging into Docker registry docker.io...
WARNING! Your password will be stored unencrypted in /home/runner/.docker/config.json.
Building Docker image docker.io/***/debug with tags $(date +%Y%m%d),latest...
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Sending build context to Docker daemon  126.5kB
```

**Comment by mr-smithers-excellent** [comment]
Hi @diepes - thanks for bringing this up. I'm happy to investigate some security improvements here. Open to any suggestions you may have.

**Comment by mr-smithers-excellent** [comment]
@diepes - it appears the [Docker team has solved for this issue](https://github.com/docker/build-push-action/issues/53) by performing a `docker logout` action by default at the conclusion of the action. This will effectively wipe the credentials from the `config.json` file and seems like a sound security best practice for this action.

**Comment by diepes** [comment]
Great, thanks for investigating the warning.
