### ISSUE TITLE
Add multi-platform support

### ISSUE THREAD

**Issue by aceberg** [mr-smithers-excellent/docker-build-push#107]
I tried to add `platform: linux/amd64,linux/arm/v7,linux/arm64`, but got only amd64 build.
Github Actions says this:

`Unexpected input(s) 'platform', valid inputs are ['image', 'tags', 'registry', 'dockerfile', 'directory', 'buildArgs', 'labels', 'target', 'username', 'password', 'gitHubOrg', 'addLatest', 'addTimestamp']`

My workflow: [https://github.com/aceberg/go-LinkSaver/blob/main/.github/workflows/docker-publish.yml](https://github.com/aceberg/go-LinkSaver/blob/main/.github/workflows/docker-publish.yml)

**Comment by mr-smithers-excellent** [comment]
@aceberg - thanks for raising an issue. The `platform` input isn't yet available in a release. Can you try pointing to `@master` instead? That should do the trick. 

I should also be able to push out a release this weekend to make this more stable.

**Comment by aceberg** [comment]
@mr-smithers-excellent , thank you! That worked. 
But only for a single platform (for example `platform: linux/arm64`)
If the platform is set to `platform: linux/amd64,linux/arm/v7,linux/arm64` the build will fail with this error:
```
Error response from daemon: "amd64,linux" is an invalid component of "linux/amd64,linux/arm/v7,linux/arm64": platform specifier component must match "^[A-Za-z0-9_-]+$": invalid argument
Error: Command failed: docker build -f Dockerfile -t docker.io/***/go-linksaver:latest -t docker.io/***/go-linksaver:0.2.0 --platform linux/amd64,linux/arm/v7,linux/arm64 .
```

As I understand, the problem is that the action doesn't use buildx, because on my desktop I can run `docker buildx build --platform linux/amd64,linux/arm/v7 -t aceberg/go-linksaver .` and it works fine

**Comment by mr-smithers-excellent** [comment]
Ahh, ok. I will need to do a bit of due diligence here to see what other changes would be necessary to migrate to `buildx`. Based on some initial research it should be fully backward compatible with `docker build`. I'll consider this as a feature request to migrate to `buildx` and prioritize accordingly.

**Comment by mr-smithers-excellent** [comment]
@aceberg - looks like you've migrated to the official Docker action in your workflow, can I assume this is no longer necessary then?

**Comment by aceberg** [comment]
@mr-smithers-excellent - yeah, thank you! Though I find your Action more convenient, it's easier to support multiplatform on official Docker Action for now

**Comment by mr-smithers-excellent** [comment]
Appreciate the kind feedback! Always open to any suggestions for improvement. Closing this for now. Thanks again!

**Comment by MykalMachon** [comment]
Hi @mr-smithers-excellent, 
**I was wondering if the multi-platform support mentioned in this thread ever made it into the main branch.** 

I'm trying to put in a PR for [Umami: an open-source GA alternative](https://github.com/umami-software/umami) to add support for ARM builds. They're [using this action as a CI step to publish their docker images](https://github.com/umami-software/umami/blob/master/.github/workflows/cd.yml#L22-L30) and it seems like this feature would be required to make that work with their current setup. 

**If not, no worries! Just don't seem to have a way to test things locally.** 
Thanks in advance.

**Comment by mr-smithers-excellent** [comment]
@MykalMachon FYI we have a renewed push to add multi-platform support to this action. I'll be looking to merge in this feature this week and cut a new release. Are there any additional requirements I should be aware for your use case to take into consideration?

**Comment by mr-smithers-excellent** [comment]
Implemented in [v6](https://github.com/mr-smithers-excellent/docker-build-push/releases/tag/v6.0)
