### ISSUE TITLE
Set output warning when running this action

### ISSUE THREAD

**Issue by kotikoB** [mr-smithers-excellent/docker-build-push#112]
<img width="1029" alt="Screenshot 2022-10-22 at 09 56 49" src="https://user-images.githubusercontent.com/31103322/197325221-3bafaf46-9bc6-4f90-b28e-dc2d1784009b.png">

**Comment by mr-smithers-excellent** [comment]
Hi @kotikoB. Thanks for bringing this to my attention. I'm not yet sure if these are commands I'm using directly or if they are pulled from dependencies. In any event, I'll get a solution for this merged before the deprecation date of May 31, 2023. Here's more info:

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by erzz** [comment]
+1 for the issue as I came here to write the same thing

To be honest, looking at your source, its seems a problem with the core github package as far as I can tell as you aren't doing anything more than `core.setOutput(...);` 🤷🏻 

But I see they have released a new version https://github.com/actions/toolkit/releases/tag/%40actions%2Fcore%401.1.0

**Comment by mr-smithers-excellent** [comment]
Super helpful! I did some digging myself and couldn't see anything obvious aside from upgrading `@actions/core`.

It seems odd they would publish deprecation warnings without an immediate solution in their own libraries. I'll watch that issue and see if anybody from the GH team chimes in.

**Comment by kotikoB** [comment]
Thank guys, waiting to try the fix once the PR is merged.

**Comment by mr-smithers-excellent** [comment]
@erzz - now that I look at the nightly e2e tests, it looks like this actually is resolved. Can you give this a try on your end using the `@master` branch?

**Comment by erzz** [comment]
Morning @mr-smithers-excellent 

Indeed the warnings are gone using @master! 🎉 

One remains about node12 actions, but the set-outputs ones are no more

**Comment by mr-smithers-excellent** [comment]
Thanks, @erzz! I'll close ticket issue then and get that other warnings cleared out.
