### ISSUE TITLE
Docker Push without build

### ISSUE THREAD

**Issue by pablo102** [mr-smithers-excellent/docker-build-push#117]
Hello!

I have ./mvnw command to build project
How to avoid docker build and make docker push with your action?

**Comment by mr-smithers-excellent** [comment]
Hi @pablo102 - sounds like you'll need to disable or remove whatever Maven build plug-in you're using for Docker builds. If you provide your pom.xml here, I can take a look.

**Comment by finbiteitops** [comment]
Thank you for the fast response, your recommendation helped!

**Comment by pablo102** [comment]
Thank you for the fast response, i did as you recommended and now the issue is solved.
