### ISSUE TITLE
Output image SHA256 digest(s)

### ISSUE THREAD

**Issue by pl4nty** [mr-smithers-excellent/docker-build-push#148]
Thanks for this excellent action! I'm using it to build platform-specific images, then manually push a multi-platform manifest. I'm avoiding buildx due to poor performance and lack of Windows support.

At the moment, the action's `outputs` only contain tags, so I have to use platform-specific tags to create the manifest. I'd like to use sha256 digests instead, so I don't have a bunch of redundant tags in my registry.

Could sha256 digests be added to the `outputs`?

**Comment by mr-smithers-excellent** [comment]
Hi @pl4nty! Appreciate the kind words. This should be a fairly simple feature to implement. Can you confirm the format these should be in? Here's an example from the [latest alpine image](https://hub.docker.com/layers/library/alpine/latest/images/sha256-3f57972158a12207fe5a2332005e6baf7bd73873e78b3f3a846df4fc93c3b7e6?context=explore):

`sha256:3f57972158a12207fe5a2332005e6baf7bd73873e78b3f3a846df4fc93c3b7e6`

Is this what you're looking for?

**Comment by pl4nty** [comment]
Yes, that's it. I'll only need a single digest, but multiplatform builds would produce multiple digests

**Comment by mr-smithers-excellent** [comment]
@pl4nty - **finally** have some time to get back to feature requests. Is this still a need?

**Comment by pl4nty** [comment]
@mr-smithers-excellent not really, I only need this for cosign now and tag-based signing is only deprecated, not removed yet. I'm also planning to migrate to buildx once Windows support lands

**Comment by fajfer** [comment]
> [@pl4nty](https://github.com/pl4nty) - **finally** have some time to get back to feature requests. Is this still a need?

I literally need the digest for the same thing @pl4nty mentioned. Looks like I need to do this manually just like he did

**Comment by mr-smithers-excellent** [comment]
@fajfer always willing to take a contribution!

**Comment by fajfer** [comment]
> [@fajfer](https://github.com/fajfer) always willing to take a contribution!

Touche, fair point:) If I proceed with using forgejo/Github Actions (this was my first one) I'll surely send something
