### ISSUE TITLE
Is it possible to cache node_modules that were installed in Dockerfile?

### ISSUE THREAD

**Issue by sandrooco** [mr-smithers-excellent/docker-build-push#205]
I need to install `sharp` inside the Dockerfile to make Next.js image optimization run properly (see [docs](https://nextjs.org/docs/messages/install-sharp)).
`sharp` is quite large and significantly increases build time. Is it possible to somehow cache this part?

**Comment by mr-smithers-excellent** [comment]
It's natively possible using the official Docker [build-push-action](https://github.com/docker/build-push-action) via `buildx`, but not yet possible using this action.
