### ISSUE TITLE
"Node.js 16 actions are deprecated" warning

### ISSUE THREAD

**Issue by fretje** [mr-smithers-excellent/docker-build-push#215]
I've searched the issues but didn't see it mentioned anywhere yet...

I get a warning on github when using this action:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: mr-smithers-excellent/docker-build-push@v6.2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by mr-smithers-excellent** [comment]
@fretje - thank you for the heads-up! I'll get this updated.
