### ISSUE TITLE
Image Build Fail

### ISSUE THREAD

**Issue by junpark12** [mr-smithers-excellent/docker-build-push#23]
Hi I received an error when i tried to build image.
I have 3 .net core project in visual studio.
Here's my project hierarchy.

-root
 -- apptest
 -- testProject
 -- APIProject

I'd like to build container an image using apptest project only.
Here's part of my github action.
i've already build and published my project on previous Job.
 
Build-And-Pubh-Docker-Iamge:
    runs-on: windows-latest
    needs: [CI]
    name: Docker Build and Push
    steps: 
      - uses: actions/checkout@v2
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: webpack artifact
          path: publish
      - name: Docker push
        uses: mr-smithers-excellent/docker-build-push@v3
        with:
          **directory: publish**
          **dockerfile: ./publish/Dockerfile**
          image: testapp/apptest
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 

I received the following error. 
denied: No matching package_file with sha256 "xxxxxx" found in repository "myorg/testapp".

What should i do? Thanks.

**Comment by mr-smithers-excellent** [comment]
Hi @junpark12 - can you download the GitHub Action build logs for this job and provide to me here?
