### ISSUE TITLE
How to push latest tag only upon releases

### ISSUE THREAD

**Issue by f18m** [mr-smithers-excellent/docker-build-push#238]
Hi @mr-smithers-excellent ,
I noticed that, according to the docs:
 https://github.com/marketplace/actions/docker-build-push-action#auto-tagging-with-gitops

the 'latest' tag is pushed only when addLatest=true. However if I set that attribute, then even feature branches will override the latest tag of e.g. my released version "1.0.0".
My need would be to push the "latest" tag only when releasing new versions (i.e. when placing a git tag). 
How can I achieve that?
Thanks!

**Comment by mr-smithers-excellent** [comment]
That sort of tagging is not supported through the action. You would have to run a step before this action and set the tag as either an environment variable or output, then set `tags` on this action accordingly.
