### ISSUE TITLE
Dockerfile unable to detect by CI 

### ISSUE THREAD

**Issue by rsarkar29** [mr-smithers-excellent/docker-build-push#26]
Even Dockerfile is there in my root directory still showing error
Repo Url :- https://github.com/rsarkar29/action
Getting below error

Run mr-smithers-excellent/docker-build-push@v4
Creating Docker image tag...
Docker tag created: master-f8f99b8
Docker image name created: docker.io/***/drupal:master-f8f99b8
Logging into Docker registry docker.io...
WARNING! Your password will be stored unencrypted in /home/runner/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/runner/work/action/action/Dockerfile: no such file or directory
##[error]Dockerfile does not exist in location Dockerfile
Building Docker image: docker.io/***/drupal:master-f8f99b8
##[error]Command failed: docker build -f Dockerfile -t docker.io/***/drupal:master-f8f99b8 .

**Comment by mr-smithers-excellent** [comment]
Looks like you were able to resolve with the official Docker action. Closing.
