### ISSUE TITLE
Passing docker options such as `--no-cache`

### ISSUE THREAD

**Issue by mikkelee** [mr-smithers-excellent/docker-build-push#282]
Currently, the docker step of our workflow is just a bunch of commands in a `run: |`, so I wanted to try updating to this much nicer action instead.

However some of our images require `--no-cache`, and thus the builds fail. Is it possible to pass such options to the build?

**Comment by mr-smithers-excellent** [comment]
What did you have in mind exactly? We could certainly add an input to govern a `--no-cache` parameter. Can you explain what you mean by "much nicer action"?

**Comment by mikkelee** [comment]
Oh, I just meant a proper Github Action is much nicer than handwriting all the docker commands myself :)

We are in the process of converting a number of setups from Travis-CI to Github Actions, and this is one that needs `--no-cache`. Perhaps others will need other docker options, so the simplest solution might be to just add something like a `docker-build-options:` input to handle cases like these?

**Comment by mikkelee** [comment]
No worries about this, we decided to use [docker/build-push-action](https://github.com/docker/build-push-action) which has a `no-cache` input
