### ISSUE TITLE
Insecure Registry Support

### ISSUE THREAD

**Issue by aztecrabbit** [mr-smithers-excellent/docker-build-push#31]
Add option to push to insecure registry

**Comment by mr-smithers-excellent** [comment]
Hi @aztecrabbit - thanks for the feedback. Can you provide an example of how you currently authenticate with an insecure registry?

**Comment by aztecrabbit** [comment]
Registry auth is using htpasswd, my server is not using ssl (http only). In my device i enable insecure registry by creating `/etc/docker/daemon.json`, inside that file is like this

```
{
  "insecure-registry": [
    "host:port"
  ]
}
```

**Comment by mr-smithers-excellent** [comment]
@aztecrabbit - I've decided not to support insecure registries, but I don't want to leave you empty-handed here. Looks like you can achieve this with the new Docker [build-push-action](https://github.com/docker/build-push-action).
