### ISSUE TITLE
Update for multiple docker tags broke existing functionality

### ISSUE THREAD

**Issue by jheckman-rt** [mr-smithers-excellent/docker-build-push#32]
The newest release seems to have broken the ability to build tag based on latest release version - my script hasn't changed but now it fails to build the tag for the docker container.

CURRENT OUTPUT:
Run mr-smithers-excellent/docker-build-push@master
  with:
    image: props
    registry: ***.dkr.ecr.us-east-2.amazonaws.com
    dockerfile: Dockerfile
  env:
    AWS_DEFAULT_REGION: us-east-2
    AWS_REGION: us-east-2
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
Docker image name created: ***.dkr.ecr.us-east-2.amazonaws.com/props
Logging into ECR region us-east-2...
WARNING! Using -*** the CLI is insecure. Use --password-stdin.
Building Docker image: ***.dkr.ecr.us-east-2.amazonaws.com/props:

PREVIOUS OUTPUT:
Run mr-smithers-excellent/docker-build-push@master
  with:
    image: props
    registry: ***.dkr.ecr.us-east-2.amazonaws.com
    dockerfile: Dockerfile
  env:
    AWS_DEFAULT_REGION: us-east-2
    AWS_REGION: us-east-2
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
Creating Docker image tag...
Docker tag created: v3.2.0
Docker image name created: ***.dkr.ecr.us-east-2.amazonaws.com/props:v3.2.0
Logging into ECR region us-east-2...
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Building Docker image: ***.dkr.ecr.us-east-2.amazonaws.com/props:v3.2.0

**Comment by mr-smithers-excellent** [comment]
@jheckman-rt - you'll need to point to the specific release you're using instead of the master branch. That should quickly resolve your issue.

Change `uses: mr-smithers-excellent/docker-build-push@master` to `uses: mr-smithers-excellent/docker-build-push@v4`

**Comment by jheckman-rt** [comment]
I will try that!  Thank you so much!

**Comment by paretje** [comment]
According to the docs of v5, this should work though:
> By default, if you do not pass a tags input this action will use an algorithm based on the state of your git repo to determine the Docker image tag.

As this issue was closed, does this mean the feature will be dropped from future versions?

**Comment by mr-smithers-excellent** [comment]
@paretje - thanks for catching this. Definitely still supporting the auto-tagging feature. Appreciate the PR, will review and comment back there.
