### ISSUE TITLE
Use another container registry

### ISSUE THREAD

**Issue by mikaeru** [mr-smithers-excellent/docker-build-push#37]
Hello there

I want to do an experiment to use azure container registry service, but when I read the readme.md, it's not upon the list
of supported registries, refrence : [https://github.com/mr-smithers-excellent/docker-build-push#docker-build--push-action](https://github.com/mr-smithers-excellent/docker-build-push#docker-build--push-action).
So, I still can use this Action workflow to deploy my codes to the azure container registry?

Thank you

**Comment by mr-smithers-excellent** [comment]
Hi @mikaeru - I have not attempted to push an image to ACR yet. Could you give it a try using this action and let me know the result? I'm happy to add support or simply documentation to clear up ACR support. Thanks!

**Comment by mikaeru** [comment]
ahhh, got it! 👍

**Comment by mikaeru** [comment]
Hi!

I've tried this action to push the image to my own acr, and it works. I can see my image in my acr repository and pull it.
There's no any problem and it runs like when i use it to push the image to my own github registry.

**Comment by mr-smithers-excellent** [comment]
@mikaeru - that's great news!  Can you provide a snippet of your GH Actions `.yaml` file so I can add to our docs?  Would greatly appreciate it.

**Comment by mikaeru** [comment]
ahh, i use the same configuration for github registry, but the credentials still from the azure (include the registry address). I'm sorry, I have been purge the repo and the repo was made for the test...

I hope you understand
