### ISSUE TITLE
Random Docker Images Tags on workflow 

### ISSUE THREAD

**Issue by ratroot92** [mr-smithers-excellent/docker-build-push#45]
every time ci cd push occurs to docker i have docker images with new random tags ....as  per commit sha i want to disable those random tags and want to push with just one tags always

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-java:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image:
        tags: v1, latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

**Comment by mr-smithers-excellent** [comment]
Hi @ratroot92 - can you upgrade to v5 and tell me if this resolves your issue?

**Comment by mr-smithers-excellent** [comment]
Issue will be resolved with an upgrade to v5 per [README breaking changes section](https://github.com/mr-smithers-excellent/docker-build-push#breaking-changes)

**Comment by ratroot92** [comment]
i am extremely thankful for your response
