### ISSUE TITLE
Feature Request: Add a parameter for the description of the package

### ISSUE THREAD

**Issue by marksalpeter** [mr-smithers-excellent/docker-build-push#46]
# Feature Request
I've noticed that many docker repos include a README associated with the release. Do you think it would be possible to add the description markdown as a parameter in this already amazing action? It might make it, dare I say, amazinger.

<img width="1440" alt="Screenshot 2021-03-01 at 19 25 21" src="https://user-images.githubusercontent.com/1033500/109541714-66189d80-7ac4-11eb-9383-9e5cd225e958.png">

**Comment by mr-smithers-excellent** [comment]
You again?! :-)

According to [this](https://github.community/t/container-registry-package-description/130640) that can be achieved through Docker labels applied in two possible approaches:

1. Dockerfile level 
```
LABEL org.opencontainers.image.description="A short text-only description that will appear on the containers page."
```
2. docker build level 
```
docker build --label "org.opencontainers.image.description=A short text-only description that will appear on the containers page."
```

If the Dockerfile approach doesn't meet your needs, I would suggest we abstract this feature request to instead add support for labels during build time.  It may be slightly easier to version-control that sort of a lengthy description in the `Dockerfile` vs the Actions `.yml` config.  Let me know your thoughts.

**Comment by marksalpeter** [comment]
Yep, me again 😅

I’m using conventional commits to autogen my changelog during my cd pipeline. So initially I though it would be nice to use that changelog in the containers read me. 

But maybe it’s better to have this be a more static description about the package in general? I’ll have to look at some popular project and see how they use this. 

Thanks for the info about opencontainers.image.description. Super valuable
