### ISSUE TITLE
Argument --target

### ISSUE THREAD

**Issue by art-cg** [mr-smithers-excellent/docker-build-push#51]
Hello,

ist there a way to specify the "--target"?
https://docs.docker.com/develop/develop-images/multistage-build/#stop-at-a-specific-build-stage

Example:
docker build -t gcr.io/test-api-platform/php:latest api --target api_platform_php

Can you built that option in your action?
https://docs.docker.com/engine/reference/commandline/build/#options

**Comment by mr-smithers-excellent** [comment]
Hi @art-cg - currently this feature is not available, but we can raise a feature request and get it incorporated.  Right now we're only supporting `--build-arg` from Docker build options.

**Comment by mr-smithers-excellent** [comment]
@art-cg - this feature will be pushed to master shortly and available in release tags `v5` and `v5.5`

**Comment by art-cg** [comment]
Thank you
