### ISSUE TITLE
Feature request: passing in build arguments

### ISSUE THREAD

**Issue by arokem** [mr-smithers-excellent/docker-build-push#6]
Thanks for creating this action! 

I would like to pass not one, but multiple build arguments to the docker build step.

I am guessing you'd have to make some changes [here](https://github.com/mr-smithers-excellent/docker-build-push/blob/master/src/docker.js#L41-L50), to pass in additional arguments to this function, but not sure I dare try doing this myself. WDYT?

**Comment by mr-smithers-excellent** [comment]
Hi @arokem - thanks for the feature request.

Definitely happy to give this a shot. Can you give me an example of what your `docker build` command looks like?

**Comment by arokem** [comment]
Well, that was fast! 😄 

Something like this: https://github.com/nipreps/dmriprep/blob/master/.circleci/config.yml#L93-L98

**Comment by mr-smithers-excellent** [comment]
Got it. Would you want to add a `--cache-from` param as well?

**Comment by arokem** [comment]
No - we probably want to remove that anyway.

**Comment by mr-smithers-excellent** [comment]
I can take a crack at this tonight - I don't foresee it being very difficult.

**Comment by arokem** [comment]
I'm getting this error: https://github.com/arokem/dmriprep/commit/079a3b2729b1f51f694b2ca5798e439d563313a0/checks?check_suite_id=401335463

**Comment by mr-smithers-excellent** [comment]
I'm wondering if the buffer on the child_process is getting overloaded. I've honestly never seen a Docker build take as long as this one, so that's my first inclination. Did `docker build` work on the master version of this GH Action? I'm doubting that the build-args would have caused this error, but want to be sure.

**Comment by arokem** [comment]
Yeah. It's a pretty long docker build (science is hard!), but it does
work with a more explicit version of the workflow:
https://github.com/arokem/dmriprep/commit/f9c966e3934d4bfd4d9d067b83185f042d6c9c8e/checks?check_suite_id=401371812

We might have to give up on using your action anyway, because (as you can
see in that PR), we need some rather granular control of the build and
pushing. Sorry for the noise.

**Comment by mr-smithers-excellent** [comment]
Looks like some pretty interesting (and meaningful) work you're tackling there!  

Even if you don't end up using it, I'm now intrigued by the problem and want to solve it. I've forked that repo and am going to adjust the buffer settings to see if that's the issue.

**Comment by mr-smithers-excellent** [comment]
Increasing the buffer size appears to have fixed this issue. See [this build](https://github.com/mr-smithers-excellent/dmriprep/commit/0104e2b1b9891518bf5615eb74984326e2c32c38/checks?check_suite_id=401449495).

I'll be incorporating these changes into a new release (even if you won't be using it). Let me know if there are any other feature requests. I definitely want this GH Action to be versatile.

**Comment by arokem** [comment]
Thank you!
