### ISSUE TITLE
Layer caching

### ISSUE THREAD

**Issue by WilfredDube** [mr-smithers-excellent/docker-build-push#73]
Is there a method of caching layers created during the building of a Dockerfile so that the workflow doesn't start from the start all the time (for some builds it takes more than an hour at a time)? Any recommendations?

**Comment by mr-smithers-excellent** [comment]
Hi @WilfredDube - caching is a tricky topic in the ephemeral ecosystem that is GitHub Actions. Short answer, caching is outside the scope of this repository and you'll need to utilize additional steps in your workflow to make this happen. This is why GitHub actions put out an action for caching - [actions/cache](https://github.com/actions/cache)

After some quick Googling, this seems to be a sane approach that I would consider:

[Build images on GitHub Actions with Docker layer caching](https://evilmartians.com/chronicles/build-images-on-github-actions-with-docker-layer-caching)
