### ISSUE TITLE
[ISSUE] Dockerfile does not exist in location Dockerfile

### ISSUE THREAD

**Issue by kumarsaroj18** [mr-smithers-excellent/docker-build-push#78]
Here is the example [Failed Workflow](https://github.com/kumarsaroj18/docker-learning-react/runs/4893277884?check_suite_focus=true), which fails when we use this action.
After debugging the source code, I found one issue with the code, where the error is thrown for non-availability of Dockerfile without looking into buildDir

> const build = (imageName, tags, buildArgs, labels, target) => {
  const dockerfile = core.getInput('dockerfile');
  const buildDir = core.getInput('directory') || '.';
  if (!fs.existsSync(dockerfile)) {
    core.setFailed("Dockerfile does not exist in location ${dockerfile}");
  }
 core.info("Building Docker image ${imageName} with tags ${tags}...");
  cp.execSync(createBuildCommand(dockerfile, imageName, tags, buildDir, buildArgs, labels, target), cpOptions);

Using this action in a different way, however, gives no issue. [Running Workflow](https://github.com/kumarsaroj18/docker-learning-react/runs/4883520467?check_suite_focus=true)
Note: Also, the error message is misleading, "does not exist in location Dockerfile", here it's not a location but a file

**Comment by mr-smithers-excellent** [comment]
If you're using the default `Dockerfile` at project root, try removing this line from `test-and-publish.yaml`

```
dockerfile: Dockerfile
```

It looks like you're using a different Dockerfile earlier in your workflow, if you want to use an alternate, try changing to:

```
dockerfile: Dockerfile.dev
```
