### ISSUE TITLE
add buildkit support?

### ISSUE THREAD

**Issue by erzz** [mr-smithers-excellent/docker-build-push#81]
Awesome action all around! Just missing one thing and thats buildkit?

as an example of an everyday Docker command not supported by the action currently:

```
COPY --chown=someuser --chmod=755 somebinary /usr/local/bin/
the --chmod option requires BuildKit. Refer to https://docs.docker.com/go/buildkit/ to learn how to build images with BuildKit enabled
Error: Command failed: docker build -f Dockerfile -t someimage:sometag
```

Then we can have lean and mean dockerfiles that likely can be relied on to build with the action as well as locally?

**Comment by mr-smithers-excellent** [comment]
Hi @erzz - thanks for the kind words and enhancement request. I have to admit I have not yet kicked the tires with buildkits yet. It looks like to enable them you must set an environment variable `DOCKER_BUILDKIT=1`. If that's the case, are you thinking this should be a workflow input that defaults to `false`?

**Comment by erzz** [comment]
sorry for the slow response - my notifications were trimmed a little heavily :)

Im not expert either - but from what I can tell, it removes nothing, only adds. But I guess most users would perhaps not care too much about it being enabled by defualt. So opt-in sounds good for starters at least?

**Comment by mr-smithers-excellent** [comment]
@erzz no problemo! I've had similar issues alert fatigue -> too little alerts :)

I'll plan on adding an input for enabling buildkit support and report back.

**Comment by mr-smithers-excellent** [comment]
@erzz this has been added & merged into master. It will also be included in the next release, which I'll cut in the next few days. For now, you can test by using:
```
- uses: mr-smithers-excellent/docker-build-push@master
```

**Comment by erzz** [comment]
Hey after a couple of months vacation - tested and working great (for my chmod context anyway)

**Comment by mr-smithers-excellent** [comment]
@erzz - this is available on both master as well as the [latest release](https://github.com/mr-smithers-excellent/docker-build-push/releases/tag/v5.7), which you can reference:

`- uses: mr-smithers-excellent/docker-build-push@v5`
or
`- uses: mr-smithers-excellent/docker-build-push@v5.7`

Thanks again for the feature request!
