### ISSUE TITLE
documentation enhancement request

### ISSUE THREAD

**Issue by simonmcnair** [mr-smithers-excellent/docker-build-push#82]
Thanks for putting this together.  Please can you add to the documentation that secrets change per environment and that the environment must be tagged for the secrets to apply.  It took me about 3 hours to figure this out.  My mistake, but could save people frustration:

    runs-on: ubuntu-latest
    environment: production

![image](https://user-images.githubusercontent.com/101189766/157640013-907b230a-49d8-4df7-81cf-3ddfb1206954.png)

**Comment by SimonMcN** [comment]
Thank you for your understanding and appreciation of my issue.  Thanks for your great work, documentation, addressing these kinds of issue and patience.  Your gift to the community and myself is appreciated.

**Comment by mr-smithers-excellent** [comment]
@simonmcnair - just to make sure I have this straight. Was your solution to simply store the `DOCKER_PASSWORD` and `DOCKER_USERNAME` as environment secrets (vs repository secrets)? Essentially you need to make sure these secrets exist in each environment you are running in your workflows (dev, staging, etc) because these environments can't access repository-level secrets?

**Comment by simonmcnair** [comment]
hi @mr-smithers-excellent .  No.  I used action secrets.  My issue was that when you create a secret github, without telling you, assigns it to 'production' environment.  This means that you are REQUIRED to add the line '    environment: production' to you github action.  This is due to the fact that github actions are designed for use in multiple environments (admirable) but nowhere does github make it mandatory to state the environment in the YAML when a secret is defined.  This means you can be in my situation where, without the leap of logic your build fails and you don't know why, and you can't troubleshoot it as secrets are hidden.

I hope this makes sense.  Cheers, Simon.

**Comment by mr-smithers-excellent** [comment]
@simonmcnair - did a little further digging on this. It looks like [using environments for deployment](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment) is only applicable for public repos or private Enterprise repos. Just curious which category you fall into, as I haven't leveraged this feature myself yet.

**Comment by mr-smithers-excellent** [comment]
@simonmcnair - thanks again for bringing this up. I've added some best practices about storing secrets in the [README](https://github.com/mr-smithers-excellent/docker-build-push#storing-secrets).

**Comment by simonmcnair** [comment]
In my opinion only api keys should be in env vars as they can be echo'd out i believe/suspect (guessing).  Username and pw are proper secrets.  This means that you MUST specify environment in your github action.  By default it is set to production but could easily be qa/preprod/dev etc. And it would use the appropriate secret for that environment.SimonOn 13 Mar 2022 20:54, Sean Smith ***@***.***> wrote:
@simonmcnair - just to make sure I have this straight. Was your solution to simply store the DOCKER_PASSWORD and DOCKER_USERNAME as environment secrets (vs repository secrets)? Essentially you need to make sure these secrets exist in each environment you are running in your workflows (dev, staging, etc) because these environments can't access repository-level secrets?

**Comment by SimonMcN** [comment]
an api key can sometimes be specified in the password field.

But yes, api keys are infinitely better than passwords.

With regard to echoing things out, you need to trust that the worker
prevents that, otherwise the only option is to host your own runner I guess
?
