### ISSUE TITLE
docker build platform option for mac m1

### ISSUE THREAD

**Issue by BaekSeungYeol** [mr-smithers-excellent/docker-build-push#95]
Hi, I'd like to build with --platform linux/amd64 option when building dockerFile. Can you give me such a setting? 
Or if I don't know, please let me know. Because I am using Mac m1, if I do not give that build option, an error appears.

**Comment by mr-smithers-excellent** [comment]
Hi @BaekSeungYeol - are you running this action on one of the [Github-hosted mac runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners) or is this a self-hosted runner? Either way, I should be able to add this optional feature/input. Let me know if this is still of interest to you. Thanks for the feature request.

**Comment by mr-smithers-excellent** [comment]
@BaekSeungYeol - this is available on `@master` if you wish to test before cutting the next release. Thanks for the feature request!

**Comment by mr-smithers-excellent** [comment]
@BaekSeungYeol - this is available on both master as well as the [latest release](https://github.com/mr-smithers-excellent/docker-build-push/releases/tag/v5.7), which you can reference:

`- uses: mr-smithers-excellent/docker-build-push@v5`
or
`- uses: mr-smithers-excellent/docker-build-push@v5.7`

Thanks again for the feature request!
