### ISSUE TITLE
Password field does not accept DOCKER_PASSWORD as env variable

### ISSUE THREAD

**Issue by SelimHorri** [mr-smithers-excellent/docker-build-push#96]
Hi,
Here defining env variables:
![env_vars_docker](https://user-images.githubusercontent.com/40203497/161866941-12d33c33-f30d-4a4c-a282-a13b040a1696.png)

problem here is when just injecting password from env, job will fail. But when injecting password from secrets, everything goes fine (as follows)
![docker_cred](https://user-images.githubusercontent.com/40203497/161868335-6e8af0fa-bc5e-415c-920d-2b46d8a3d394.png)

Would you please proceed further ?

Kindest,
Selim

**Comment by mr-smithers-excellent** [comment]
Hi @SelimHorri - its really advisable to store sensitive credentials like usernames and password within secrets. Looks like you might have a syntax issue with your `DOCKER_USERNAME` environment variable. Trying replacing with `${{ env.DOCKER_USERNAME}}`

**Comment by SelimHorri** [comment]
Hi @mr-smithers-excellent 
Yes, agreed, problem solved
Thanks for your continuous support
