### ISSUE TITLE
Failure when the package.json has a private dependency

### ISSUE THREAD

**Issue by nicktackes** [mr-smithers-excellent/docker-build-push#97]
I have a private dependency repo that i was forced to store in GPR in order to get github actions to successfully do an npm install from a repo that contained this private dependency.  When using the docker-build-push i seem to run into the same issue when the npm install is invoked.  The steps are straight forward in that i checkout code, setup node, authenticate GPR and then docker build push.  The problem is that npm install has no ability to obtain the private repo dependency.

    steps:

    - name: Check out code
      uses: actions/checkout@v3
      with:
        token: '${{ secrets.GITHUB_TOKEN }}'
      env:
        GITHUB_TOKEN: '${{github.token}}'

    - uses: actions/setup-node@v3
      with:
        node-version: 12
        registry-url: https://npm.pkg.github.com/

    - name: authenticate GPR
      env:
        GH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      run: |
        echo "//npm.pkg.github.com/:_authToken=${GH_TOKEN}" > ~/.npmrc
        printf "PAT length: $(echo $GH_TOKEN |wc -c)\n"

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: admin-worker/${{ github.ref_name }}
        tags: ${{ github.ref_name }}
        registry: XXXXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

![Screen Shot 2022-05-17 at 2 47 13 PM](https://user-images.githubusercontent.com/654285/168915703-4f2dc499-f1d4-4b94-b462-a0b8283c58f9.png)

**Comment by mr-smithers-excellent** [comment]
Hi @nicktackes - it looks like this is an issue accessing your private NPM repository before the Docker build actually takes place. Typically a build of this nature would have a step before the `Build & push Docker image` step where you run an `npm install` and `npm run build` to produce some sort of build directory that is referenced in your `Dockerfile`. Is there a reason you're skipping this step? Can you provide an example of your `Dockerfile`?

I am not immediately seeing anything that would lead me to believe this is a bug within this GitHub Action, but I'm happy to continue looking if you can provide the above info. Thanks!

**Comment by nicktackes** [comment]
thanks for the reply.  I've been struggling with the security scoping within github actions and i understand what you are saying here.  I was doing an npm install inside the dockerfile so by moving that into the scope of the github action yml i was able to successfully npm install the private repo containing the private repo dependency.  thank you.

**Comment by mr-smithers-excellent** [comment]
Ahh that makes sense. Glad I could help!
